version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "4567:4567"

  mongodb:
    image: mongo:bionic
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
      - mongodb:/data/db
    env_file:
      - .env

volumes:
  mongodb:
